// js/pdf.js
// PDF / print export for a meeting

import { formatDate, escapeHtml } from './utils.js';

/**
 * Open the browser print dialog with a formatted meeting report.
 * Builds a hidden iframe with print-optimised HTML, triggers print,
 * then removes the iframe.
 */
function printMeeting(meeting) {
  const html = buildPrintHtml(meeting);
  const frame = document.createElement('iframe');
  frame.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:1px;height:1px;border:0';
  document.body.appendChild(frame);
  frame.contentDocument.write(html);
  frame.contentDocument.close();
  frame.contentWindow.focus();
  setTimeout(() => {
    frame.contentWindow.print();
    setTimeout(() => document.body.removeChild(frame), 1000);
  }, 250);
}

function buildPrintHtml(m) {
  const date = formatDate(m.date);
  const time = [m.time, m.endTime].filter(Boolean).join(' – ');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${escapeHtml(m.title)} — Meeting Report</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, Helvetica, sans-serif; font-size: 11pt; color: #111; padding: 20mm 25mm; }
  h1 { font-size: 18pt; margin-bottom: 4pt; }
  h2 { font-size: 13pt; margin: 14pt 0 4pt; border-bottom: 1px solid #ccc; padding-bottom: 3pt; }
  h3 { font-size: 11pt; margin: 8pt 0 2pt; }
  .meta { color: #555; font-size: 10pt; margin-bottom: 6pt; }
  table { width: 100%; border-collapse: collapse; margin-top: 6pt; font-size: 10pt; }
  th, td { border: 1px solid #ccc; padding: 4pt 6pt; text-align: left; }
  th { background: #f0f0f0; font-weight: bold; }
  ul { margin-left: 16pt; }
  li { margin-bottom: 2pt; }
  .sig-img { max-width: 180pt; max-height: 60pt; border: 1px solid #ccc; }
  .badge { display: inline-block; padding: 1pt 5pt; border-radius: 3pt; font-size: 9pt; font-weight: bold; }
  .footer { margin-top: 20pt; font-size: 9pt; color: #888; text-align: center; }
  @page { margin: 15mm; }
</style>
</head>
<body>

<h1>${escapeHtml(m.title)}</h1>
<div class="meta">
  ${escapeHtml(date)}${time ? ' &nbsp;|&nbsp; ' + escapeHtml(time) : ''}
  ${m.location ? ' &nbsp;|&nbsp; ' + escapeHtml(m.location) : ''}
  ${m.company ? ' &nbsp;|&nbsp; ' + escapeHtml(m.company) : ''}
</div>
<div class="meta">
  Organizer: <strong>${escapeHtml(m.organizer || '—')}</strong>
  &nbsp;|&nbsp; Type: <strong>${escapeHtml(m.type || '—')}</strong>
  &nbsp;|&nbsp; Status: <strong>${escapeHtml(m.status || '—')}</strong>
</div>

${m.agenda && m.agenda.length ? `
<h2>Agenda</h2>
<ol>
  ${m.agenda.map(a => `<li>${escapeHtml(a)}</li>`).join('')}
</ol>` : ''}

${m.attendees && m.attendees.length ? `
<h2>Attendance</h2>
<table>
  <thead><tr><th>Name</th><th>Role</th><th>Company</th><th>Email</th><th>Present</th></tr></thead>
  <tbody>
    ${m.attendees.map(a => `
    <tr>
      <td>${escapeHtml(a.name)}</td>
      <td>${escapeHtml(a.role)}</td>
      <td>${escapeHtml(a.company)}</td>
      <td>${escapeHtml(a.email)}</td>
      <td>${a.present ? '✓' : ''}</td>
    </tr>`).join('')}
  </tbody>
</table>` : ''}

${m.minutes ? `
<h2>Meeting Minutes</h2>
<p style="white-space:pre-wrap">${escapeHtml(m.minutes)}</p>` : ''}

${m.decisions && m.decisions.length ? `
<h2>Decisions</h2>
<table>
  <thead><tr><th>#</th><th>Decision</th><th>Made By</th></tr></thead>
  <tbody>
    ${m.decisions.map((d, i) => `
    <tr>
      <td>${i + 1}</td>
      <td>${escapeHtml(d.description)}</td>
      <td>${escapeHtml(d.madeBy)}</td>
    </tr>`).join('')}
  </tbody>
</table>` : ''}

${m.actionItems && m.actionItems.length ? `
<h2>Action Items</h2>
<table>
  <thead><tr><th>#</th><th>Task</th><th>Assignee</th><th>Due Date</th><th>Priority</th><th>Status</th></tr></thead>
  <tbody>
    ${m.actionItems.map((a, i) => `
    <tr>
      <td>${i + 1}</td>
      <td>${escapeHtml(a.description)}</td>
      <td>${escapeHtml(a.assignee)}</td>
      <td>${escapeHtml(a.dueDate)}</td>
      <td>${escapeHtml(a.priority)}</td>
      <td>${escapeHtml(a.status)}</td>
    </tr>`).join('')}
  </tbody>
</table>` : ''}

${m.attendees && m.attendees.some(a => a.signatureData) ? `
<h2>Signatures</h2>
${m.attendees.filter(a => a.signatureData).map(a => `
<div style="margin-bottom:10pt;">
  <h3>${escapeHtml(a.name)}</h3>
  <img class="sig-img" src="${a.signatureData}" alt="Signature of ${escapeHtml(a.name)}">
</div>`).join('')}` : ''}

<div class="footer">
  Generated by Methodz Meeting Manager &mdash; ${new Date().toLocaleDateString('en-CA')}
</div>

</body>
</html>`;
}

export { printMeeting };
